import React from 'react'
import styles from './Reset.module.css'
import Input from '../../../../components/base/input/input'
import Button from '../../../../components/base/button/button'
import Link from 'next/link'
import Head from 'next/head'
import { motion } from 'framer-motion'

const Reset = () => {
    return (
        <>
            <Head>
                <title>Chatopia | Reset Password</title>
                <meta name="description" content="Generated by Chatopia" />
            </Head>
            <div className={`${styles.reset}`}>
                <motion.div
                    initial={{
                        scale: 0.5,
                        opacity: 0
                    }}
                    animate={{
                        scale: 1,
                        opacity: 1,
                        transition: {
                            delay: 0.2
                        }
                    }}
                >
                    <div className={`${styles.reset_container}`}>
                        <div className={`${styles.title}`}>
                            <p><Link href={'/auth/user/signin'}>{`<`}</Link></p>
                            <h1>Forgot Password</h1>
                        </div>
                        <h4>You'll get messages soon on your e-mail </h4>
                        <form className={`${styles.forms}`}>
                            <Input
                                label={'Email'}
                                placeholder={'youremail@gmail.com'}
                                type={'email'}
                                name={'email'}
                                id={'email'}
                                autofocus={true}
                            />
                            <Button
                                text={'Send'}
                            />
                        </form>
                    </div>
                </motion.div>
            </div>
        </>
    )
}

export default Reset